name: flutter_google_auth
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.1+1
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.13.0+1
  simple_animations: ^1.1.3
  page_transition: ^1.1.4
  flutter_datetime_picker: 1.2.5
  intl: ^0.16.1
  animated_background: ^1.0.5
  curved_navigation_bar: ^0.3.2
  sweetalert: any

  contacts_service: ^0.4.6
  permission_handler: ^5.0.0+hotfix.5
  animated_floatactionbuttons: ^0.1.0
  android_alarm_manager: ^0.4.5+10
  twilio_flutter: ^0.0.4
  flutter_local_notifications: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
    - family: Sofia
      fonts:
          - asset: fonts/Sofia-Regular.ttf

